baseurl: "/soil-genesis"
url: "https://ms-smx.github.io"

title: Soil Genesis
description: Seed Recovery Protocol

markdown: kramdown

plugins:
  - jekyll-feed

collections:

  seeds:
    output: true
    permalink: /sementi/:name/

  resources:
    output: false

  recipes:
    output: true
    permalink: /ricette/:name/

  lost_seeds:
    output: true
    permalink: /sementi/perdute/:name/

  perennials:
    output: true
    permalink: /sementi/perenni/:name/

  spontaneous:
    output: true
    permalink: /sementi/spontanee/:name/

  logs:
    output: true
    permalink: /log/:name/