baseurl: "/soil-genesis"
url: "https://ms-smx.github.io"

title: Soil Genesis
description: Seed Recovery Protocol

markdown: kramdown

plugins:
  - jekyll-feed

collections:

  seeds:
    output: true
    permalink: /sementi/:name/