required:

  - id

  - nome_comune

  - nome_scientifico

  - famiglia

  - cover

  - provenienza

  - stato_conservazione

  - ciclo_vita

  - impollinazione

optional:

  - descrizione

  - habitat

  - bibliografia

  - ricette

  - annotazioni